<a href="https://colab.research.google.com/github/graviada/colabRepo/blob/master/Stepik%20courses%20(2022)/Computer%20vision%20by%20Samsung/work_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### **Gradient descent**

In [1]:
import torch

In [2]:
# min = 1.
# max = 4.

# #create tensor with random values in range (min, max)
# rand_tensor = (max-min)*torch.rand((2, 5)) + min
# rand_tensor

tensor([[1.3769, 3.3946, 3.7833, 1.7678, 1.0258],
        [3.0547, 1.2144, 3.6910, 1.3065, 3.6750]])

In [12]:
w = torch.tensor([[5., 10.], [1., 2.]], requires_grad=True)

function = torch.log(torch.log(w + 7)).prod()

function.backward()
print(w.grad)

tensor([[0.0201, 0.0109],
        [0.0449, 0.0351]])


In [52]:
w = torch.tensor([[5., 10.], [1., 2.]], requires_grad=True)
alpha = 0.001

# function = (w + 7).log().log().prod()
for _ in range(500):
    function = (w + 7).log().log().prod()
    function.backward()
    w.data -= alpha * w.grad
    w.grad.zero_()

print(w.data)

tensor([[4.9900, 9.9948],
        [0.9775, 1.9825]])


### **Linear regression**